### ISSUE TITLE
Upload data file: word2vec_google300_for_NYT.pkl

### ISSUE THREAD

**Issue by huan** [zixia/xi-lstm#5]
We need `word2vec_google300_for_NYT.pkl` to be uploaded to https://github.com/zixia/xi-lstm/releases/edit/v0.0.1

See:
https://github.com/zixia/xi-lstm/blob/81f534b8f8a1731944f9358b7e85b0fcb70ede57/src/main.py#L400-L415

**Comment by huyingxi** [comment]
I just uploaded the file to release.

**Comment by huan** [comment]
Awesome!
