### ISSUE TITLE
Update make run command to support main_Standard_LSTM.py

### ISSUE THREAD

**Issue by huyingxi** [zixia/xi-lstm#7]
I just uploaded main_Standard_LSTM.py that differs from main.py by replacing our two LSTMCell with standard LSTMCell.
So you can modify make run command to support the running of this new program.

**Comment by huan** [comment]
Yes, madam.

Now
```
make run-standard
```
can do it.

**Comment by huyingxi** [comment]
嘻嘻嘻～Thx.
