### ISSUE TITLE
update make run command for main_MultiLabelLoss.py & make download for multi_label.zip

### ISSUE THREAD

**Issue by huyingxi** [zixia/xi-lstm#9]
> 1).   main_MultiLabelLoss.py 
> This file has modified the loss function compared to the previous one(main.py) and is used to train multi-label classification model.

> 2).   multi_label.zip
> This dataset is used in the multi-label classification model

Please update make run & make download commands.
😊😊☺️☺️

**Comment by huan** [comment]
### make run

The following modifications in `Makefile` do the trick for you:

```
run-multi:
	python3 src/main_multi_label_loss.py
```

### make download

This following modifications in `scripts/download.sh` do the trick for you:

```
if [ -d multi_label/train_test ]
then
    echo 'multi_label/train_test exists'
else
    curl -LO https://github.com/zixia/xi-lstm/releases/download/v0.0.1/multi_label.zip
    unzip multi_label.zip
    rm multi_label.zip
fi
```
